(defpackage staubliTX60-msg
  (:use cl
        roslisp-msg-protocol)
  (:export
   "<SETJOINTSRESULT>"
   "<SETCARTESIANACTIONGOAL>"
   "<SETCARTESIANGOAL>"
   "<SETJOINTTRAJECTORYFEEDBACK>"
   "<SETCARTESIANACTION>"
   "<SETJOINTSFEEDBACK>"
   "<SETJOINTTRAJECTORYACTION>"
   "<SETJOINTSACTION>"
   "<SETCARTESIANACTIONFEEDBACK>"
   "<SETJOINTTRAJECTORYACTIONFEEDBACK>"
   "<SETJOINTTRAJECTORYACTIONRESULT>"
   "<SETJOINTSACTIONRESULT>"
   "<SETJOINTSGOAL>"
   "<SETJOINTTRAJECTORYGOAL>"
   "<STAUBLIMOVEMENTPARAMS>"
   "<JOINTTRAJECTORYPOINT>"
   "<SETCARTESIANFEEDBACK>"
   "<SETCARTESIANRESULT>"
   "<SETJOINTTRAJECTORYACTIONGOAL>"
   "<SETJOINTSACTIONFEEDBACK>"
   "<SETJOINTTRAJECTORYRESULT>"
   "<SETJOINTSACTIONGOAL>"
   "<SETCARTESIANACTIONRESULT>"
  ))

