(defpackage staubliTX60-msg
  (:use cl
        roslisp-msg-protocol)
  (:export
   "<SETJOINTSRESULT>"
   "<SETCARTESIANACTIONGOAL>"
   "<SETCARTESIANGOAL>"
   "<SETCARTESIANACTION>"
   "<SETJOINTSFEEDBACK>"
   "<SETJOINTSACTION>"
   "<SETCARTESIANACTIONFEEDBACK>"
   "<SETJOINTSACTIONRESULT>"
   "<SETJOINTSGOAL>"
   "<SETCARTESIANFEEDBACK>"
   "<SETCARTESIANRESULT>"
   "<SETJOINTSACTIONFEEDBACK>"
   "<SETJOINTSACTIONGOAL>"
   "<SETCARTESIANACTIONRESULT>"
  ))

