; Auto-generated. Do not edit!


(in-package staubliTX60-msg)


;//! \htmlinclude SetCartesianActionGoal.msg.html

(defclass <SetCartesianActionGoal> (ros-message)
  ((header
    :reader header-val
    :initarg :header
    :type roslib-msg:<Header>
    :initform (make-instance 'roslib-msg:<Header>))
   (goal_id
    :reader goal_id-val
    :initarg :goal_id
    :type actionlib_msgs-msg:<GoalID>
    :initform (make-instance 'actionlib_msgs-msg:<GoalID>))
   (goal
    :reader goal-val
    :initarg :goal
    :type staubliTX60-msg:<SetCartesianGoal>
    :initform (make-instance 'staubliTX60-msg:<SetCartesianGoal>)))
)
(defmethod serialize ((msg <SetCartesianActionGoal>) ostream)
  "Serializes a message object of type '<SetCartesianActionGoal>"
  (serialize (slot-value msg 'header) ostream)
  (serialize (slot-value msg 'goal_id) ostream)
  (serialize (slot-value msg 'goal) ostream)
)
(defmethod deserialize ((msg <SetCartesianActionGoal>) istream)
  "Deserializes a message object of type '<SetCartesianActionGoal>"
  (deserialize (slot-value msg 'header) istream)
  (deserialize (slot-value msg 'goal_id) istream)
  (deserialize (slot-value msg 'goal) istream)
  msg
)
(defmethod ros-datatype ((msg (eql '<SetCartesianActionGoal>)))
  "Returns string type for a message object of type '<SetCartesianActionGoal>"
  "staubliTX60/SetCartesianActionGoal")
(defmethod md5sum ((type (eql '<SetCartesianActionGoal>)))
  "Returns md5sum for a message object of type '<SetCartesianActionGoal>"
  "d38b87822f7d363993083a1290a2c163")
(defmethod message-definition ((type (eql '<SetCartesianActionGoal>)))
  "Returns full string definition for message of type '<SetCartesianActionGoal>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%SetCartesianGoal goal~%~%================================================================================~%MSG: roslib/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: staubliTX60/SetCartesianGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 x~%float64 y~%float64 z~%float64 rx~%float64 ry~%float64 rz~%int32   lineCtrl~%~%~%"))
(defmethod serialization-length ((msg <SetCartesianActionGoal>))
  (+ 0
     (serialization-length (slot-value msg 'header))
     (serialization-length (slot-value msg 'goal_id))
     (serialization-length (slot-value msg 'goal))
))
(defmethod ros-message-to-list ((msg <SetCartesianActionGoal>))
  "Converts a ROS message object to a list"
  (list '<SetCartesianActionGoal>
    (cons ':header (header-val msg))
    (cons ':goal_id (goal_id-val msg))
    (cons ':goal (goal-val msg))
))
