; Auto-generated. Do not edit!


(in-package staubliTX60-msg)


;//! \htmlinclude SetJointsGoal.msg.html

(defclass <SetJointsGoal> (ros-message)
  ((j
    :reader j-val
    :initarg :j
    :type (vector float)
   :initform (make-array 0 :element-type 'float :initial-element 0.0))
   (params
    :reader params-val
    :initarg :params
    :type staubliTX60-msg:<StaubliMovementParams>
    :initform (make-instance 'staubliTX60-msg:<StaubliMovementParams>)))
)
(defmethod serialize ((msg <SetJointsGoal>) ostream)
  "Serializes a message object of type '<SetJointsGoal>"
  (let ((__ros_arr_len (length (slot-value msg 'j))))
    (write-byte (ldb (byte 8 0) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_arr_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_arr_len) ostream))
  (map nil #'(lambda (ele) (let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (write-byte (ldb (byte 8 0) bits) ostream)
    (write-byte (ldb (byte 8 8) bits) ostream)
    (write-byte (ldb (byte 8 16) bits) ostream)
    (write-byte (ldb (byte 8 24) bits) ostream)
    (write-byte (ldb (byte 8 32) bits) ostream)
    (write-byte (ldb (byte 8 40) bits) ostream)
    (write-byte (ldb (byte 8 48) bits) ostream)
    (write-byte (ldb (byte 8 56) bits) ostream)))
    (slot-value msg 'j))
  (serialize (slot-value msg 'params) ostream)
)
(defmethod deserialize ((msg <SetJointsGoal>) istream)
  "Deserializes a message object of type '<SetJointsGoal>"
  (let ((__ros_arr_len 0))
    (setf (ldb (byte 8 0) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_arr_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_arr_len) (read-byte istream))
    (setf (slot-value msg 'j) (make-array __ros_arr_len))
    (let ((vals (slot-value msg 'j)))
      (dotimes (i __ros_arr_len)
(let ((bits 0))
    (setf (ldb (byte 8 0) bits) (read-byte istream))
    (setf (ldb (byte 8 8) bits) (read-byte istream))
    (setf (ldb (byte 8 16) bits) (read-byte istream))
    (setf (ldb (byte 8 24) bits) (read-byte istream))
    (setf (ldb (byte 8 32) bits) (read-byte istream))
    (setf (ldb (byte 8 40) bits) (read-byte istream))
    (setf (ldb (byte 8 48) bits) (read-byte istream))
    (setf (ldb (byte 8 56) bits) (read-byte istream))
    (setf (aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (deserialize (slot-value msg 'params) istream)
  msg
)
(defmethod ros-datatype ((msg (eql '<SetJointsGoal>)))
  "Returns string type for a message object of type '<SetJointsGoal>"
  "staubliTX60/SetJointsGoal")
(defmethod md5sum ((type (eql '<SetJointsGoal>)))
  "Returns md5sum for a message object of type '<SetJointsGoal>"
  "c6dbba60f19ac53528a89658f795669b")
(defmethod message-definition ((type (eql '<SetJointsGoal>)))
  "Returns full string definition for message of type '<SetJointsGoal>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64[] j~%StaubliMovementParams params~%~%================================================================================~%MSG: staubliTX60/StaubliMovementParams~%uint8 movementType~%#float64 distBlendPrev #meters unused right now - default .05~%#float64 distBlendNext #meters unused right now - default .05~%float64 jointVelocity #0-1~%float64 jointAcc #0-1~%float64 jointDec #0-1~%float64 endEffectorMaxTranslationVel #meters/sec?~%float64 endEffectorMaxRotationalVel #radians/sec~%~%~%~%~%"))
(defmethod serialization-length ((msg <SetJointsGoal>))
  (+ 0
     4 (reduce #'+ (slot-value msg 'j) :key #'(lambda (ele) (declare (ignorable ele)) (+ 8)))
     (serialization-length (slot-value msg 'params))
))
(defmethod ros-message-to-list ((msg <SetJointsGoal>))
  "Converts a ROS message object to a list"
  (list '<SetJointsGoal>
    (cons ':j (j-val msg))
    (cons ':params (params-val msg))
))
