; Auto-generated. Do not edit!


(in-package staubliTX60-msg)


;//! \htmlinclude SetJointsActionGoal.msg.html

(defclass <SetJointsActionGoal> (ros-message)
  ((header
    :reader header-val
    :initarg :header
    :type roslib-msg:<Header>
    :initform (make-instance 'roslib-msg:<Header>))
   (goal_id
    :reader goal_id-val
    :initarg :goal_id
    :type actionlib_msgs-msg:<GoalID>
    :initform (make-instance 'actionlib_msgs-msg:<GoalID>))
   (goal
    :reader goal-val
    :initarg :goal
    :type staubliTX60-msg:<SetJointsGoal>
    :initform (make-instance 'staubliTX60-msg:<SetJointsGoal>)))
)
(defmethod serialize ((msg <SetJointsActionGoal>) ostream)
  "Serializes a message object of type '<SetJointsActionGoal>"
  (serialize (slot-value msg 'header) ostream)
  (serialize (slot-value msg 'goal_id) ostream)
  (serialize (slot-value msg 'goal) ostream)
)
(defmethod deserialize ((msg <SetJointsActionGoal>) istream)
  "Deserializes a message object of type '<SetJointsActionGoal>"
  (deserialize (slot-value msg 'header) istream)
  (deserialize (slot-value msg 'goal_id) istream)
  (deserialize (slot-value msg 'goal) istream)
  msg
)
(defmethod ros-datatype ((msg (eql '<SetJointsActionGoal>)))
  "Returns string type for a message object of type '<SetJointsActionGoal>"
  "staubliTX60/SetJointsActionGoal")
(defmethod md5sum ((type (eql '<SetJointsActionGoal>)))
  "Returns md5sum for a message object of type '<SetJointsActionGoal>"
  "ea2ec080b0753688c6d7164c28552f71")
(defmethod message-definition ((type (eql '<SetJointsActionGoal>)))
  "Returns full string definition for message of type '<SetJointsActionGoal>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%SetJointsGoal goal~%~%================================================================================~%MSG: roslib/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: staubliTX60/SetJointsGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64[] j~%~%~%"))
(defmethod serialization-length ((msg <SetJointsActionGoal>))
  (+ 0
     (serialization-length (slot-value msg 'header))
     (serialization-length (slot-value msg 'goal_id))
     (serialization-length (slot-value msg 'goal))
))
(defmethod ros-message-to-list ((msg <SetJointsActionGoal>))
  "Converts a ROS message object to a list"
  (list '<SetJointsActionGoal>
    (cons ':header (header-val msg))
    (cons ':goal_id (goal_id-val msg))
    (cons ':goal (goal-val msg))
))
