(defpackage staubliTX60-srv
  (:use cl
        roslisp-msg-protocol)
  (:export
   "INVKINEMATICS"
   "<INVKINEMATICS-REQUEST>"
   "<INVKINEMATICS-RESPONSE>"
   "GETROTMAT"
   "<GETROTMAT-REQUEST>"
   "<GETROTMAT-RESPONSE>"
   "GETCARTESIAN"
   "<GETCARTESIAN-REQUEST>"
   "<GETCARTESIAN-RESPONSE>"
   "FWDKINEMATICS"
   "<FWDKINEMATICS-REQUEST>"
   "<FWDKINEMATICS-RESPONSE>"
   "GETJOINTS"
   "<GETJOINTS-REQUEST>"
   "<GETJOINTS-RESPONSE>"
  ))

